# Generated by Django 6.0.2 on 2026-03-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта'),
        ),
    ]
